name: firebase_chat_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.0
  country_code_picker: ^3.0.0
  equatable: ^2.0.5
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  google_sign_in: ^6.1.4
  google_sign_in_web: ^0.12.0+3

  image_picker: ^1.0.2
  intl: ^0.18.1
  photo_view: ^0.14.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ 
    
